version: '2'
services:
  management1:
    image: mysql/mysql-cluster
    volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.2
  ndb1:
    image: mysql/mysql-cluster
    volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.3
  ndb2:
    image: mysql/mysql-cluster
    volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.4
  mysql1:
    image: mysql/mysql-cluster
    ports:
      - "3306:3306"
    volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql1:db
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.11

networks:
 mysqlcluster:
  driver: bridge
  ipam:
   config:
    - subnet: 172.28.0.0/16
